import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import Hero from "../components/Hero";
import styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Yebin's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@1,500&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Hero />
      </Wrapper>
    </>
  );
}

const Wrapper = styled.div`
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
`;
